export function getEmojiForIcon(iconStr: string | undefined): string {
  if (!iconStr) return '🍽️';
  
  // If it's already an emoji (length 1 or 2 typically)
  const trimmed = iconStr.trim();
  // Use regex to test if string contains emoji
  const emojiRegex = /\p{Extended_Pictographic}/u;
  if (emojiRegex.test(trimmed) || trimmed.length <= 2) {
    return trimmed;
  }

  // Map common text words generated by previous AI versions to emojis
  const lower = trimmed.toLowerCase();
  
  const iconMap: Record<string, string> = {
    bread: '🍞',
    sauce: '🥫',
    juice: '🧃',
    jam: '🍯',
    peanut: '🥜',
    candy: '🍬',
    soda: '🥤',
    cheese: '🧀',
    pudding: '🍮',
    chocolate: '🍫',
    milk: '🥛',
    meat: '🥩',
    fish: '🐟',
    fruit: '🍎',
    vegetable: '🥦',
    cake: '🍰',
    cookie: '🍪',
    yogurt: '🍦',
    icecream: '🍨',
    snack: '🥨',
    chips: '🍟',
    soup: '🥣',
    water: '💧',
    coffee: '☕',
    tea: '🍵',
    egg: '🥚',
    butter: '🧈',
    oil: '🫒',
    nut: '🌰',
    seed: '🌻',
    spice: '🌶️',
    herb: '🌿',
    default: '🍽️'
  };

  for (const [key, emoji] of Object.entries(iconMap)) {
    if (lower.includes(key)) return emoji;
  }

  return iconMap['default'];
}
